### ISSUE TITLE
Accordion animation

### ISSUE THREAD

**Issue by auban** [circlingthesun/angular-foundation-6#41]
Hello,

How to animate the accordion?

Thanks

Auban

**Comment by circlingthesun** [comment]
I've updated the accordion to use ng-hide. You should be able to animate it with something like this now:

```scss
.accordion-content {
  max-height: 499px;
  transition: 0.3s all ease-in-out;

  &.ng-hide {
    max-height: 0;
  }

  &.ng-hide-add,
  &.ng-hide-remove {
    display: block !important;
  }
}
```
